import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import BackgroundAnimDecor from "@/components/BackgroundAnimDecor/BackgroundAnimDecor";

export const metadata: Metadata = {
  title: "Jacek Kuczyński",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-blackDimmed">
        <Navbar />
        <BackgroundAnimDecor />
        {/* <div className="w-full h-screen"></div>
        <div className="w-full h-screen"></div>
        <div className="w-full h-screen"></div>
        <div className="hidden">{children}</div> */}
        {children}
      </body>
    </html>
  );
}
