import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Jacek Kuczyński",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-bold font-raleway ">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
