import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${inter.className} bg-blackdimmed`}>
        <div className="block tooSmall:hidden text-heading-two uppercase text-whitedimmed font-bold">
          Device too small
        </div>
        <div className="hidden tooSmall:block">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
